export const Products = [
  {
    id: 1,
    title: "Pantalon en denim wide leg - Bleu",
    description: "Ce pantalon donne un style décontracté à toutes vos tenues !",
    price: "15.00",
    image: [
      "/products/jeans/pantalon-en-denim.webp",
      "/products/jeans/pantalon-en-denim2.webp",
      "/products/jeans/pantalon-en-denim3.webp",
    ],
    slug: "pantalon-en-denim-wide-leg-Bleu",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 2,
    title: "T-shirt droit en jersey uni - blanc",
    description:
      "Celui qui s'associe aussi bien avec un jean qu’un pantalon plus habillé.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-droit-en-jersey.webp",
      "/products/t-shirts/t-shirt-droit-en-jersey2.webp",
      "/products/t-shirts/t-shirt-droit-en-jersey3.webp",
    ],
    slug: "t-shirt-droit-en-jersey-uni-blanc",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 3,
    title: "Veste esprit campus - Noir",
    description:
      "La veste esprit campus, un indispensable de votre dressing, en molleton gratté (doux et chaud) !",
    price: "25.00",
    image: [
      "/products/vestes/veste-esprit-campus.webp",
      "/products/vestes/veste-esprit-campus2.webp",
      "/products/vestes/veste-esprit-campus3.webp",
    ],
    slug: "veste-esprit-campus-Noir",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 4,
    title: "Chaussures de ville - Noir",
    description:
      "Chaussures de ville en cuir, à lacets, avec semelle en caoutchouc.",
    price: "35.00",
    image: [
      "/products/chaussures/chaussures-de-ville-noir.webp",
      "/products/chaussures/chaussures-de-ville-noir2.webp",
      "/products/chaussures/chaussures-de-ville-noir3.webp",
    ],
    slug: "chaussures-de-ville-Noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 5,
    title: "Jean slim - L32 - stone used",
    description:
      "Le basique qu'il faut avoir absolument dans son dressing, couleur beige !",
    price: "17",
    image: [
      "/products/jeans/jean-slim.webp",
      "/products/jeans/jean-slim2.webp",
      "/products/jeans/jean-slim3.webp",
    ],
    slug: "jean-slim-L32-stone-used",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["red", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 6,
    title: "Jean skinny fit / coupe très ajustée - Rince",
    description: "Un jean skinny comme une seconde peau !",
    price: "19.99",
    image: [
      "/products/jeans/jean-skinny-fit.webp",
      "/products/jeans/jean-skinny-fit2.webp",
      "/products/jeans/jean-skinny-fit3.webp",
    ],
    slug: "jean-skinny-fit-coupe-tres-ajustee-Rince",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 7,
    title: "Jean slim à 5 poches - bleu marine",
    description: "Un jean slim, parfait pour lui et ses mouvements !",
    price: "12.99",
    image: [
      "/products/jeans/jean-slim-a-5-poches.webp",
      "/products/jeans/jean-slim-a-5-poches2.webp",
      "/products/jeans/jean-slim-a-5-poches3.webp",
    ],
    slug: "jean-slim-a-5-poches-bleu-marine",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 8,
    title: "T-shirt droit en jersey uni - blanc",
    description: "Best sellers* : L'incontournable T-shirt basique.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-droit.webp",
      "/products/t-shirts/t-shirt-droit2.webp",
      "/products/t-shirts/t-shirt-droit3.webp",
    ],

    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 9,
    title: "T-shirt droit en jersey uni - Noir",
    description:
      "Les meilleures ventes : L'incontournable pour un bon basique.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-uni-en-jersey.webp",
      "/products/t-shirts/t-shirt-uni-en-jersey2.webp",
      "/products/t-shirts/t-shirt-uni-en-jersey3.webp",
    ],
    slug: "t-shirt-droit-en-jersey-uni-Noir",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 10,
    title: "T-shirt col V - noir",
    description: "Un basique très confortable !",
    price: "6.00",
    image: [
      "/products/t-shirts/t-shirt-col-v.webp",
      "/products/t-shirts/t-shirt-col-v2.webp",
      "/products/t-shirts/t-shirt-col-v3.webp",
    ],
    slug: "t-shirt-col-v-noir",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 11,
    title: "Gilet sans manches en sherpa - Marron",
    description: "Le gilet de base pour les plus petits et les plus grands.",
    price: "12.00",
    image: [
      "/products/vestes/gilet-sans-manches.webp",
      "/products/vestes/gilet-sans-manches2.webp",
      "/products/vestes/gilet-sans-manches3.webp",
    ],
    slug: "gilet-sans-manches-en-sherpa-marron",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 12,
    title: "Veste en jean avec manches en molleton - Bleu",
    description: "Veste en jean avec manches en molleton - Bleu",
    price: "25.00",
    image: [
      "/products/vestes/veste-en-jean.webp",
      "/products/vestes/veste-en-jean2.webp",
      "/products/vestes/veste-en-jean3.webp",
    ],
    slug: "veste-en-jean-avec-manches-en-molleton-bleu",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 13,
    title: "Veste bi matière - Kaki",
    description: "Veste bi matière - Kaki",
    price: "25.00",
    image: [
      "/products/vestes/veste-bi-matiere.webp",
      "/products/vestes/veste-bi-matiere2.webp",
      "/products/vestes/veste-bi-matiere3.webp",
    ],
    slug: "veste-bi-matiere-kaki",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 14,
    title: "Bottines type chelsea - Noir",
    description: "Bottines type chelsea - Noir",
    price: "25.00",
    image: [
      "/products/chaussures/bottines-type-chelsea-noir.webp",
      "/products/chaussures/bottines-type-chelsea-noir2.webp",
      "/products/chaussures/bottines-type-chelsea-noir3.webp",
    ],
    slug: "bottines-type-chelsea-noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 15,
    title: "Escarpins babies vernis - Noir",
    description: "Escarpins babies vernis - Noir",
    price: "25.00",
    image: [
      "/products/chaussures/escarpins-babies-vernis-noir.webp",
      "/products/chaussures/escarpins-babies-vernis-noir2.webp",
      "/products/chaussures/escarpins-babies-vernis-noir3.webp",
    ],
    slug: "escarpins-babies-vernis-noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 16,
    title: "Chaussures de randonnée - kaki",
    description: "Chaussures de randonnée - kaki",
    price: "25.00",
    image: [
      "/products/chaussures/chaussures-de-randonnee.webp",
      "/products/chaussures/chaussures-de-randonnee2.webp",
      "/products/chaussures/chaussures-de-randonnee3.webp",
    ],
    slug: "chaussures-de-randonnee-kaki",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
];

export const CategoriesProducts = [
  {
    id: 1,
    slug: "jeans",
    title: "Jeans",
    img: "../public/home/jean-flarebootcut.webp",
    Products: [
      {
        id: 1,
        title: "JEAN",
        description: "Jean skinny",
        price: "19.99",
        image: [
          "/home/jean-flarebootcut.webp",
          "/home/veste-matelassee.webp",
          "/home/tennis-lacets.webp",
        ],
        slug: "jean-skinny",
        catSlug: "jeans",
        cat: "jeans",
        size: ["S", "M", "L"],
        color: ["white", "black", "blue"],
        inStock: true,
        active: true,
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 2,
    slug: "t-shirts",
    title: "T-shirts",
    img: "../public/home/t-shirt-en-coton.webp",
    Products: [
      {
        id: 1,
        title: "T-SHIRT",
        description: "T-shirt en coton",
        price: "10",
        image: [
          "/home/t-shirt-en-coton.webp",
          "/home/jean-flarebootcut.webp",
          "/home/veste-matelassee.webp",
        ],
        slug: "t-shirt-en-coton",
        catSlug: "t-shirts",
        cat: "t-shirts",
        size: ["S", "M", "L"],
        color: ["white", "black"],
        inStock: true,
        active: true,
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 3,
    slug: "vestes",
    title: "Vestes",
    img: "../public/home/veste-blazer.webp",
    Products: [
      {
        id: 1,
        title: "VESTE",
        description: "Veste en jean",
        price: "19.99",
        image: [
          "/home/veste-matelassee.webp",
          "/home/tennis-lacets.webp",
          "/home/t-shirt-en-coton.webp",
        ],
        slug: "veste-en-jean",
        catSlug: "vestes",
        cat: "vestes",
        size: ["S", "M", "L"],
        color: ["white", "black", "blue"],
        inStock: true,
        active: true,
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 4,
    slug: "chaussures",
    title: "Chaussures",
    img: "../public/home/tennis-lacets.webp",
    Products: [
      {
        id: 1,
        title: "TENNIS",
        description: "Tennis en toile",
        price: "19.99",
        image: [
          "/home/tennis-lacets.webp",
          "/home/t-shirt-en-coton.webp",
          "/home/jean-flarebootcut.webp",
        ],
        slug: "tennis-en-toile",
        catSlug: "chaussures",
        cat: "chaussures",
        size: ["S", "M", "L"],
        color: ["white", "black", "blue"],
        inStock: true,
        active: true,
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
];

export const CategoriesPosts = [
  {
    id: 1,
    slug: "jeans",
    title: "Jeans",
    img: "",
    Posts: [
      {
        id: 1,
        image: "/home/2.jpg",
        title: "Jean Levis Comment choisir ?",
        description:
          "Le jean est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.",
        slug: "jean-levis-comment-choisir",
        catSlug: "jeans",
        cat: '{"id":1,"slug":"jeans","title":"Jeans","img":"","Posts":[{"id":1,"image":"/home/2.jpg","title":"Jean Levis Comment choisir ?","description":"Le jean est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.","slug":"jean-levis-comment-choisir","catSlug":"jeans","cat":"jeans","active":true,"createdAt":"2021-05-01T00:00:00.000Z"}],"Products":[{"id":1,"title":"JEAN","description":"Jean skinny","price":"19.99","image":["/home/jean-flarebootcut.webp","/home/veste-matelassee.webp","/home/tennis-lacets.webp"],"slug":"jean-skinny","catSlug":"jeans","cat":"jeans","size":["S","M","L"],"color":["white","black","blue"],"inStock":true,"active":true,"createdAt":"2021-05-01T00:00:00.000Z"}],"active":true,"createdAt":"2021-05-01T00:00:00.000Z"}',
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 2,
    slug: "t-shirts",
    title: "T-shirts",
    img: "",
    Posts: [
      {
        id: 1,
        image: "/home/1.jpg",
        title: "Comment choisir son t-shirt ?",
        description:
          "Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.",
        slug: "comment-choisir-son-t-shirt",
        catSlug: "t-shirts",
        cat: '{"id":2,"slug":"t-shirts","title":"T-shirts","img":"","Posts":[{"id":2,"image":"/home/1.jpg","title":"Comment choisir son t-shirt ?","description":"Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.","slug":"comment-choisir-son-t-shirt","catSlug":"t-shirts","cat":"{\\"id\\":2,\\"slug\\":\\"t-shirts\\",\\"title\\":\\"T-shirts\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":2,\\"image\\":\\"/home/1.jpg\\",\\"title\\":\\"Comment choisir son t-shirt ?\\",\\"description\\":\\"Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.\\",\\"slug\\":\\"comment-choisir-son-t-shirt\\",\\"catSlug\\":\\"t-shirts\\"}]}"}]}',
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 3,
    slug: "vestes",
    title: "Vestes",
    img: "",
    Posts: [
      {
        id: 1,
        image: "/home/4.jpg",
        title: "Comment choisir sa veste ?",
        description:
          "La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.",
        slug: "comment-choisir-sa-veste",
        catSlug: "vestes",
        cat: '{"id":3,"slug":"vestes","title":"Vestes","img":"","Posts":[{"id":3,"image":"/home/4.jpg","title":"Comment choisir sa veste ?","description":"La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.","slug":"comment-choisir-sa-veste","catSlug":"vestes","cat":"{\\"id\\":3,\\"slug\\":\\"vestes\\",\\"title\\":\\"Vestes\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":3,\\"image\\":\\"/home/4.jpg\\",\\"title\\":\\"Comment choisir sa veste ?\\",\\"description\\":\\"La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.\\",\\"slug\\":\\"comment-choisir-sa-veste\\",\\"catSlug\\":\\"vestes\\"}]}"}]}',
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
  {
    id: 4,
    slug: "chaussures",
    title: "Chaussures",
    img: "",
    Posts: [
      {
        id: 1,
        image: "/home/3.jpg",
        title: "Comment choisir ses chaussures ?",
        description:
          "Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.",
        slug: "comment-choisir-ses-chaussures",
        catSlug: "chaussures",
        cat: '{"id":4,"slug":"chaussures","title":"Chaussures","img":"","Posts":[{"id":4,"image":"/home/3.jpg","title":"Comment choisir ses chaussures ?","description":"Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.","slug":"comment-choisir-ses-chaussures","catSlug":"chaussures","cat":"{\\"id\\":4,\\"slug\\":\\"chaussures\\",\\"title\\":\\"Chaussures\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":4,\\"image\\":\\"/home/3.jpg\\",\\"title\\":\\"Comment choisir ses chaussures ?\\",\\"description\\":\\"Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.\\",\\"slug\\":\\"comment-choisir-ses-chaussures\\",\\"catSlug\\":\\"chaussures\\"}]}"}]}',
        createdAt: "2021-05-01T00:00:00.000Z",
      },
    ],
  },
];

export const Posts = [
  {
    id: 1,
    image: "/home/2.jpg",
    title: "Jean Levis Comment choisir ?",
    description:
      "Le jean est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.",
    content: "Choisir le jean parfait peut transformer votre garde-robe, et les Levi's sont des classiques intemporels. Mais avec tant de styles disponibles, comment trouver celui qui vous convient le mieux ? Voici un guide pour vous aider à naviguer dans l'univers des jeans Levi's. 1. Comprendre les différents modèles Levi's Les jeans Levi's sont célèbres pour leur gamme variée de coupes et de styles. Du classique 501 au moderne 711, chaque modèle a ses caractéristiques uniques. Voici un aperçu des modèles populaires :a. Levi's 501 Original Le modèle emblématique, le 501 Original, est connu pour sa coupe droite classique et sa toile denim robuste. Parfait pour un look décontracté et intemporel. b. Levi's 511 Slim Avec une coupe slim moderne, le Levi's 511 offre un équilibre parfait entre ajustement et confort. Idéal pour ceux qui préfèrent un style plus ajusté. c. Levi's 721 High Rise Skinny Pour une silhouette élégante et moderne, le Levi's 721 est un jean taille haute avec une coupe skinny flatteuse. Parfait pour mettre en valeur vos courbes. 2. Trouver la bonne taille et coupe Lorsque vous choisissez un jean Levi's, la taille et la coupe sont cruciales. Voici quelques conseils pour vous guider : a. Prenez vos mesures Mesurez votre tour de taille et votre longueur de jambe pour trouver la taille idéale. Les guides de tailles Levi's sont souvent disponibles en ligne pour vous aider. b. Essayez différents styles N'hésitez pas à essayer plusieurs modèles pour trouver celui qui vous va le mieux. Parfois, une coupe différente peut changer complètement l'ajustement. 3. Considérez le denim et les finitions Le denim Levi's varie en poids et en finition, ce qui peut influencer le confort et l'apparence du jean. Certains jeans sont pré-lavés pour un aspect vintage, tandis que d'autres ont un denim plus rigide qui se moule à votre corps avec le temps. En conclusion, choisir le bon jean Levi's demande un peu de recherche et d'essais, mais une fois que vous trouvez celui qui vous va comme un gant, il deviendra un incontournable de votre garde-robe. N'oubliez pas d'explorer les différentes coupes, tailles et finitions pour trouver votre jean parfait !",
    slug: "jean-levis-comment-choisir",
    catSlug: "jeans",
    cat: '{"id":1,"slug":"jeans","title":"Jeans","img":"","Posts":[{"id":1,"image":"/home/2.jpg","title":"Jean Levis Comment choisir ?","description":"Le jean est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.","slug":"jean-levis-comment-choisir","catSlug":"jeans","cat":"jeans","active":true,"createdAt":"2021-05-01T00:00:00.000Z"}],"Products":[{"id":1,"title":"JEAN","description":"Jean skinny","price":"19.99","image":["/home/jean-flarebootcut.webp","/home/veste-matelassee.webp","/home/tennis-lacets.webp"],"slug":"jean-skinny","catSlug":"jeans","cat":"jeans","size":["S","M","L"],"color":["white","black","blue"],"inStock":true,"active":true,"createdAt":"2021-05-01T00:00:00.000Z"}],"active":true,"createdAt":"2021-05-01T00:00:00.000Z"}',
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 2,
    image: "/home/1.jpg",
    title: "Comment choisir son t-shirt ?",
    description:
      "Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.",
    content: "",
    slug: "comment-choisir-son-t-shirt",
    catSlug: "t-shirts",
    cat: '{"id":2,"slug":"t-shirts","title":"T-shirts","img":"","Posts":[{"id":2,"image":"/home/1.jpg","title":"Comment choisir son t-shirt ?","description":"Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.","slug":"comment-choisir-son-t-shirt","catSlug":"t-shirts","cat":"{\\"id\\":2,\\"slug\\":\\"t-shirts\\",\\"title\\":\\"T-shirts\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":2,\\"image\\":\\"/home/1.jpg\\",\\"title\\":\\"Comment choisir son t-shirt ?\\",\\"description\\":\\"Le t-shirt est un incontournable de la garde-robe masculine. Il est donc important de bien le choisir.\\",\\"slug\\":\\"comment-choisir-son-t-shirt\\",\\"catSlug\\":\\"t-shirts\\"}]}"}]}',
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 3,
    image: "/home/4.jpg",
    title: "Comment choisir sa veste ?",
    description:
      "La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.",
    content: "",
    slug: "comment-choisir-sa-veste",
    catSlug: "vestes",
    cat: '{"id":3,"slug":"vestes","title":"Vestes","img":"","Posts":[{"id":3,"image":"/home/4.jpg","title":"Comment choisir sa veste ?","description":"La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.","slug":"comment-choisir-sa-veste","catSlug":"vestes","cat":"{\\"id\\":3,\\"slug\\":\\"vestes\\",\\"title\\":\\"Vestes\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":3,\\"image\\":\\"/home/4.jpg\\",\\"title\\":\\"Comment choisir sa veste ?\\",\\"description\\":\\"La veste est un incontournable de la garde-robe masculine. Il est donc important de bien la choisir.\\",\\"slug\\":\\"comment-choisir-sa-veste\\",\\"catSlug\\":\\"vestes\\"}]}"}]}',
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 4,
    image: "/home/3.jpg",
    title: "Comment choisir ses chaussures ?",
    description:
      "Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.",
    content: "",
    slug: "comment-choisir-ses-chaussures",
    catSlug: "chaussures",
    cat: '{"id":4,"slug":"chaussures","title":"Chaussures","img":"","Posts":[{"id":4,"image":"/home/3.jpg","title":"Comment choisir ses chaussures ?","description":"Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.","slug":"comment-choisir-ses-chaussures","catSlug":"chaussures","cat":"{\\"id\\":4,\\"slug\\":\\"chaussures\\",\\"title\\":\\"Chaussures\\",\\"img\\":\\"\\",\\"Posts\\":[{\\"id\\":4,\\"image\\":\\"/home/3.jpg\\",\\"title\\":\\"Comment choisir ses chaussures ?\\",\\"description\\":\\"Les chaussures sont un incontournable de la garde-robe masculine. Il est donc important de bien les choisir.\\",\\"slug\\":\\"comment-choisir-ses-chaussures\\",\\"catSlug\\":\\"chaussures\\"}]}"}]}',
    createdAt: "2021-05-01T00:00:00.000Z",
  },
];

export const Comments = [
  {
    id: 1,
    user: "Tobby",
    userEmail: "tobby@gmail.com",
    commentaire:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, voluptatibus!",
    postSlug: "",
    post: "",
    createdAt: "2021-05-01T00:00:00.000Z",
  },
];

export const Slides = [
  {
    id: 1,
    image: "/home/slide1.jpg",
    title: "TENDANCE",
    description: "Découvrez notre collection de t-shirts",
  },
  {
    id: 2,
    image: "/home/slide2.jpg",
    title: "TENDANCE",
    description: "Découvrez notre collection de jeans",
  },
  {
    id: 3,
    image: "/home/slide3.jpg",
    title: "TENDANCE",
    description: "Découvrez notre collection de vestes",
  },
];

export const Orders = [
  {
    id: 1,
    createdAt: "2021-06-08T09:47:48.000Z",
    total: "20",
    products: [
      {
        id: 1,
        title: "T-shirt",
        price: "10",
        image: "/home/1.jpg",
        quantity: 1,
      },
      {
        id: 2,
        title: "Jean",
        price: "10",
        image: "/home/2.jpg",
        quantity: 1,
      },
    ],
    status: "En cours",
    intent_id: "aaaa",
  },
  {
    id: 2,
    createdAt: "2021-06-08T09:47:48.000Z",
    total: "50",
    products: [
      {
        id: 1,
        title: "T-shirt",
        price: "10",
        image: "/home/1.jpg",
        quantity: 1,
      },
      {
        id: 2,
        title: "Jean",
        price: "10",
        image: "/home/2.jpg",
        quantity: 1,
      },
      {
        id: 3,
        title: "Veste",
        price: "30",
        image: "/home/4.jpg",
        quantity: 1,
      },
    ],
    status: "Terminé",
    intent_id: "aaaa",
  },
];
